nodeLinker: node-modules

packageExtensions:
  "@chromatic-com/storybook@*":
    dependencies:
      "@neoconfetti/react": "*"
      "strip-ansi": "*"
      "filesize": "*"
  "@storybook/addon-a11y@*":
    dependencies:
      "storybook": "*"
  "@storybook/addon-onboarding@*":
    dependencies:
      "storybook": "*"
  "storybook@*":
    dependencies:
      "@storybook/global": "*"
